# Configuration of the used Arduino board:
BOARD_TAG    = uno
MONITOR_PORT=/dev/ttyACM0

# Configuration for different location of Arduino Sketch application.

#ARDUINO_DIR   = /usr/share/arduino
#USER_LIB_PATH=$(HOME)/sketchbook/libraries

# Configuration of Arduino libraries. 

# If not definied the Arduino makefile will search for available libraries.
#ARDUINO_LIBS = Rp6

ARDMK_DIR=$(HOME)/git/Arduino-Makefile
include $(ARDMK_DIR)/Arduino.mk
